version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgres/data
    networks:
      - infra-networks
    
networks:
  infra-networks:
    driver: bridge