default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  user: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: heath_history_api_development

test:
  <<: *default
  database: heath_history_api_test

production:
  <<: *default
  database: heath_history_api_production
  username: heath_history_api
  password: <%= ENV["HEATH_HISTORY_API_DATABASE_PASSWORD"] %>
